name: 1365-backend
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - sqlalchemy
      - psycopg[binary]
      - pydantic
      - alembic
      - httpx
      - python-dotenv
