name: 1365-backend
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - sqlalchemy
      - psycopg[binary]
      - pydantic
      - alembic
      - httpx
      - python-dotenv
      - langchain-core
      - langchain-community
      - langchain-huggingface
      - langchain-ollama
      - langchain-openai
      - tqdm
      - sentence-transformers
      - numpy
      - faiss-cpu
