name: Fetch 1365 data

on:
  workflow_dispatch:
  schedule:
    # KST 00/04/08/12/16/20  →  UTC 15/19/23/03/07/11
    - cron: "0 3,7,11,15,19,23 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: fetch-1365
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: npm i axios xml2js
      - name: Run fetch
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          SIDO_CODE: "6110000"
          GUGUN_CODE: ""
          PROGRM_STTUS_SE: "2"
          USE_NOTICE_RANGE: "false"
          RECRUITING_ONLY: "false"
          PER: "100"
          MAX_PAGES: "50"
          DETAIL_CONCURRENCY: "16"
          DETAIL_DELAY_MS: "0"
          MAX_DETAIL: "999999"
        run: node scripts/fetch_1365.mjs
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/1365.json docs/data/recruit_cache.json
          git commit -m "chore(data): refresh 1365.json" || echo "no changes"
          git push
